use_frameworks!

target 'testKit_Example' do
  pod 'testKit', :path => '../'

  target 'testKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
